version: '3.3'
services:

  iris-https:
    build:
      context: .
    image: iris-https:latest
    hostname: iris-https
    command: -b "sudo service apache2 start"
    ports:
    - "51773:51773" # 51773 is the superserver default port
    - "52773:52773" # 52773 is the webserver/management portal port
    - "443:443"

